"""criacao inicial das tabelas

Revision ID: cec60c10d638
Revises: 
Create Date: 2026-09-08 19:17:05.132205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec60c10d638'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMINISTRADOR', 'TECNICO', name='perfilusuario', native_enum=False, length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=30), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('conselho', sa.String(length=20), nullable=False),
    sa.Column('numero_conselho', sa.String(length=30), nullable=False),
    sa.Column('uf_conselho', sa.String(length=2), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('documento_path', sa.String(length=255), nullable=False),
    sa.Column('selfie_documento_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANALISE', 'APROVADA', 'REJEITADA', 'RESPONDIDA', name='statussolicitacao', native_enum=False, length=20), nullable=False),
    sa.Column('observacao_interna', sa.Text(), nullable=True),
    sa.Column('motivo_rejeicao', sa.Text(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('consentimento_lgpd', sa.Boolean(), nullable=False),
    sa.Column('consentimento_versao', sa.String(length=20), nullable=False),
    sa.Column('consentimento_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('analise_iniciada_at', sa.DateTime(), nullable=True),
    sa.Column('analisado_at', sa.DateTime(), nullable=True),
    sa.Column('respondido_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_email'), 'solicitacoes', ['email'], unique=False)
    op.create_index(op.f('ix_solicitacoes_numero_conselho'), 'solicitacoes', ['numero_conselho'], unique=False)
    op.create_index(op.f('ix_solicitacoes_protocolo'), 'solicitacoes', ['protocolo'], unique=True)
    op.create_index(op.f('ix_solicitacoes_status'), 'solicitacoes', ['status'], unique=False)
    op.create_table('comunicacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.Enum('EMAIL', 'WHATSAPP', name='canalcomunicacao', native_enum=False, length=20), nullable=False),
    sa.Column('destinatario', sa.String(length=150), nullable=False),
    sa.Column('status_envio', sa.Enum('SUCESSO', 'FALHA', name='statusenvio', native_enum=False, length=20), nullable=False),
    sa.Column('enviado_por', sa.Integer(), nullable=True),
    sa.Column('enviado_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['enviado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comunicacoes_solicitacao_id'), 'comunicacoes', ['solicitacao_id'], unique=False)
    op.create_table('historico_solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('status_anterior', sa.String(length=20), nullable=True),
    sa.Column('status_novo', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_solicitacoes_solicitacao_id'), 'historico_solicitacoes', ['solicitacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_solicitacoes_solicitacao_id'), table_name='historico_solicitacoes')
    op.drop_table('historico_solicitacoes')
    op.drop_index(op.f('ix_comunicacoes_solicitacao_id'), table_name='comunicacoes')
    op.drop_table('comunicacoes')
    op.drop_index(op.f('ix_solicitacoes_status'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_protocolo'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_numero_conselho'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_email'), table_name='solicitacoes')
    op.drop_table('solicitacoes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
